export const retos =
  [
    {
      id: 1,
      title: 'Expanding Cards',
      image: './assets/img/image1.png',
      description: 'HTML5, JavaScript, CSS',
      url: 'https://angie-sanchez7.github.io/1-slider-images/',
    },
    {
      id: 2,
      title: 'Progress Step',
      image: './assets/img/image2.png',
      description: 'HTML5, JavaScript, CSS',
      url: 'https://angie-sanchez7.github.io/2-progress-step/',
    },
    {
      id: 3,
      title: 'Open Dog',
      image: './assets/img/image3.png',
      description: 'HTML5, JavaScript, CSS',
      url: 'https://angie-sanchez7.github.io/open-dog/',
    },
    {
      id: 4,
      title: 'Hidden Search',
      image: './assets/img/image4.png',
      description: 'HTML5, JavaScript, CSS',
      url: 'https://angie-sanchez7.github.io/hidden-search/',
      
    },
    {
      id: 5,
      title: 'Blurring',
      image: './assets/img/image5.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://angie-sanchez7.github.io/Blurring/',
    },
    {
      id: 6,
      title: 'Drag Drop',
      image: './assets/img/image6.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://angie-sanchez7.github.io/Drag-Drop/',
    },
    {
      id: 7,
      title: 'Auto Text',
      image: './assets/img/image7.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://angie-sanchez7.github.io/Auto-text/',
    },
    {
      id: 8,
      title: 'Hoverboard',
      image: './assets/img/image8.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://hoverboard-eta.vercel.app/',
    },
    {
      id: 9,
      title: 'Scroll Animation',
      image: './assets/img/image9.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://scroll-animation-wheat.vercel.app/',
    },
    {
      id: 10,
      title: 'Form Input',
      image: './assets/img/image10.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://form-input.vercel.app/',
    },
    {
      id: 11,
      title: 'Dad Jokes',
      image: './assets/img/image11.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://jokes-one.vercel.app/',
    },
    {
      id: 12,
      title: 'Soung Board',
      image: './assets/img/image12.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://sound-board-one.vercel.app/',
    },
    {
      id: 13,
      title: 'Live User',
      image: './assets/img/image13.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://live-user.vercel.app/',
    },
    {
      id: 14,
      title: 'Button Effect',
      image: './assets/img/image14.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://button-effect.vercel.app/',
    },
    {
      id: 15,
      title: 'Background Slider',
      image: './assets/img/image15.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://background-slider-kohl.vercel.app/',
    },
    {
      id: 16,
      title: 'Kinet Loader',
      image: './assets/img/image16.png',
      description: 'HTML5, CSS',
      url:'https://kinet-loader.vercel.app/',
    },
    {
      id: 17,
      title: 'Netflix',
      image: './assets/img/image17.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://netflix-nine-eta.vercel.app/',
    },
    {
      id: 18,
      title: 'Pokedex',
      image: './assets/img/image18.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://angie-sanchez7.github.io/Pokedex/',
    },
    {
      id: 19,
      title: 'Home',
      image: './assets/img/image19.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://angie-sanchez7.github.io/View-home/',
    },
    {
      id: 20,
      title: 'Random Choice',
      image: './assets/img/image20.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://random-flax.vercel.app/',
    },
    {
      id: 21,
      title: 'Quiz',
      image: './assets/img/image21.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://quiz-liart-eta.vercel.app/',
    },
    {
      id: 22,
      title: 'Sticky Navigation',
      image: './assets/img/image22.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://sticky-tau.vercel.app/',
    },
    {
      id: 23,
      title: 'Drink Water',
      image: './assets/img/image23.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://drink-water-five.vercel.app/',
    },
    {
      id: 24,
      title: 'Feedback Emotions',
      image: './assets/img/image24.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://feed-theta.vercel.app/',
    },
    {
      id: 25,
      title: 'Github Profile',
      image: './assets/img/image25.png',
      description: 'HTML5, JavaScript, CSS',
      url:'https://github-ochre.vercel.app/',
    },
  ]

export default retos;